import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import SidebarLayout from "@/components/layout/sidebar/SidebarLayout";

const ClientProvider = dynamic(() => import("@/providers/ClientProvider"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarLayout pageTitle="Keremet chat adminstration">
          <ClientProvider>{children}</ClientProvider>
        </SidebarLayout>
      </body>
    </html>
  );
}
